FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build-env

LABEL maintainer="Stef Heyenrath"

WORKDIR /app

# copy csproj and restore as distinct layers
COPY StandAlone.NETCoreApp.csproj ./
RUN dotnet restore

# copy everything else and build
COPY *.cs ./
RUN dotnet publish -c Release -r alpine-x64 -o out \
  --self-contained true \
  /p:PublishSingleFile=true

# build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine
# resolve CVE-2023-5363 and CVE-2023-5678
RUN apk upgrade libssl3 libcrypto3 --no-cache
WORKDIR /app
COPY --from=build-env /app/out ./
EXPOSE 80
ENTRYPOINT ["./wiremock-net", "--Urls", "http://*:80"]
CMD ["--WireMockLogger", "WireMockConsoleLogger"]

# Just some info:
# build with : docker build -t sheyenrath/wiremock.net-alpine .
# run with   : docker run --rm -p 9091:80 sheyenrath/wiremock.net-alpine
